### ISSUE TITLE
Should lazyload implements srcset?

### ISSUE THREAD

**Issue by vvo** [vvo/lazyload#38]
Should lazyload shim http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/?

Vote here

**Comment by lyrixx** [comment]
yes :)

**Comment by vvo** [comment]
@lyrixx Want this project? I am not maintaining it :D

**Comment by lyrixx** [comment]
@vvo No thanks :) This is very kind, but I already maintain too many OSS
